# Site settings
title: Steven Bamford
email: steven@stevenbamford.com
description: "Just playing at the moment."
baseurl: ""
url: "http://bamford.github.io"

# Build settings
markdown: kramdown
permalink: pretty
